#!/usr/bin/env python3
"""Regenerate .bin/docker/* from per-server SSOTs.

Derives the four docker-only manifests under .bin/docker/ from the editable
sources of truth:

  - server/fastify/package.json     ->  .bin/docker/pnpm-workspace.yaml
                                        .bin/docker/package.json   (static)
                                        .bin/docker/.npmrc          (static)
  - server/fastapi/pyproject.toml   ->  .bin/docker/pyproject.docker.toml
                                        (renamed off `pyproject.toml` to
                                        dodge Dependency Graph auto-scan;
                                        see the header inside that file)

Used by .github/workflows/release.yml to guarantee that release/<X> always
carries docker manifests that match the per-server manifests bit-for-bit,
even if a contributor on main forgot to update them after adding/removing
a sibling dep.

Two modes:

  --apply  (default)  Write the four .bin/docker/ files. Idempotent.
  --check             Compute the expected content and diff it against the
                      files on disk. Exits 0 if equal, 1 if any drift.
                      Reserved for a future CI gate on main; not wired
                      anywhere yet.

Python 3.11+ (stdlib only — tomllib).
"""
from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]  # mta-ployglot-server/
SRV_FASTIFY = ROOT / "server" / "fastify" / "package.json"
SRV_FASTAPI = ROOT / "server" / "fastapi" / "pyproject.toml"
OUT_DIR = ROOT / ".bin" / "docker"

OUT_PNPM_WS = OUT_DIR / "pnpm-workspace.yaml"
OUT_PKG_JSON = OUT_DIR / "package.json"
OUT_NPMRC = OUT_DIR / ".npmrc"
OUT_PYPROJECT = OUT_DIR / "pyproject.docker.toml"

# --- File headers (comment blocks emitted at the top of each output file) ---

_HEADER_PNPM_WS = """\
# pnpm-workspace.yaml — Docker-only workspace manifest for Dockerfile.fastify.
#
# Why this file is in .bin/docker/ and not at the repo root:
#   pnpm walks UP from any package directory looking for an enclosing
#   workspace root. A `pnpm-workspace.yaml` committed at the repo root
#   would be picked up by host-side `pnpm install` runs that
#   Makefile.lang.node fires inside individual siblings — see the warning
#   block at Makefile.lang.node:7-15. Tucking the file one level deep
#   under .bin/docker/ keeps it discoverable for Dockerfile.fastify's
#   `COPY` and invisible to pnpm's host-side walk-up.
#
# Generated by .bin/docker/regenerate.py from server/fastify/package.json.
# DO NOT EDIT BY HAND. To change the member list, edit the per-server
# manifest and run `python .bin/docker/regenerate.py --apply`.
# The release workflow auto-regenerates this file before assembling
# release/<X>, so a stale committed copy on main self-heals at release.
#
# The file paths below are relative to /application (the WORKDIR the
# Dockerfile COPYs this to), NOT to .bin/docker/ on disk.
"""

_HEADER_NPMRC = """\
# .npmrc — Docker-only pnpm config for Dockerfile.fastify.
#
# COPY'd to /application/.npmrc alongside pnpm-workspace.yaml + package.json.
# Settings mirror the inline block the Dockerfile used to fabricate at
# build time. They apply only inside the container; host workflows
# continue to use their own ~/.npmrc / per-sibling .npmrc.
#
# Generated by .bin/docker/regenerate.py (static content — no per-server
# inputs). DO NOT EDIT BY HAND.
"""

_HEADER_PYPROJECT = """\
# pyproject.docker.toml — Docker-only Poetry manifest for Dockerfile.fastapi.
#
# Why the unusual filename (not the conventional `pyproject.toml`):
#   GitHub's Dependency Graph submission auto-discovers any file named
#   exactly `pyproject.toml` and tries to resolve its dependencies against
#   the manifest's directory. The 9 `path = "./ployglots/<sibling>/..."`
#   entries below only resolve from /application/ inside the container,
#   where Dockerfile.fastapi COPYs this file. From the host's .bin/docker/
#   directory, those paths point nowhere — so Dependency Graph runs fail
#   with `path_dependencies_not_reachable`. Renaming to
#   pyproject.docker.toml dodges the exact-name auto-discovery; the
#   Dockerfile renames it back to pyproject.toml during COPY.
#
# Mirrors server/fastapi/pyproject.toml so the Dockerfile can resolve
# every editable sibling from a single root file at
# /application/pyproject.toml instead of cd'ing into server/fastapi/.
#
# Why this file is in .bin/docker/ and not at the repo root:
#   The root of mta-ployglot-server has no Python project today (Python
#   work lives under server/fastapi/, plus per-sibling packages/py
#   trees). Adding a pyproject.toml at repo root would change which
#   directory poetry considers "the project" when invoked from the repo
#   root on the host — surprising contributors and tooling alike.
#   Tucking the file under .bin/docker/ keeps it visible for
#   Dockerfile.fastapi's COPY and inert on the host (poetry from any
#   host directory won't pick it up).
#
# Generated by .bin/docker/regenerate.py from server/fastapi/pyproject.toml
# with path-dep paths rewritten `./ployglots/<sibling>/...` (relative to
# /application/, where the Dockerfile COPYs this file). The release
# workflow auto-regenerates this before assembling release/<X>, so a
# stale committed copy on main self-heals at release.
# DO NOT EDIT BY HAND.
"""

# --- Static-content emitters ---

_STATIC_PKG_JSON = {
    "name": "mta-fastify-workspace-root",
    "version": "0.0.0",
    "private": True,
    "description": (
        "Docker-only pnpm workspace root used by Dockerfile.fastify. "
        "COPY'd to /application/package.json at build time. "
        "See .bin/docker/pnpm-workspace.yaml for the member-package list. "
        "Lives under .bin/docker/ (not at repo root) so pnpm's directory "
        "walk-up cannot find it on the host — Makefile.lang.node's "
        "per-sibling install strategy stays uncontested. "
        "Generated by .bin/docker/regenerate.py — do not edit by hand."
    ),
    "engines": {"node": ">=20"},
}

_STATIC_NPMRC_LINES = [
    "link-workspace-packages=deep",
    "prefer-workspace-packages=true",
    "shared-workspace-lockfile=true",
    "auto-install-peers=false",
    "strict-peer-dependencies=false",
    "node-linker=hoisted",
]

_FASTIFY_WORKSPACE_FIRST_ENTRY = "server/fastify"
_FILE_DEP_PREFIX = "file:../../"


def build_pnpm_workspace() -> str:
    pkg = json.loads(SRV_FASTIFY.read_text())
    deps = pkg.get("dependencies", {})
    sibling_paths: list[str] = []
    for spec in deps.values():
        if isinstance(spec, str) and spec.startswith(_FILE_DEP_PREFIX + "ployglots/"):
            sibling_paths.append(spec[len(_FILE_DEP_PREFIX):])
    lines = [_HEADER_PNPM_WS.rstrip(), "packages:", f"  - {_FASTIFY_WORKSPACE_FIRST_ENTRY}"]
    for p in sibling_paths:
        lines.append(f"  - {p}")
    return "\n".join(lines) + "\n"


def build_pkg_json() -> str:
    return json.dumps(_STATIC_PKG_JSON, indent=2) + "\n"


def build_npmrc() -> str:
    return _HEADER_NPMRC.rstrip() + "\n" + "\n".join(_STATIC_NPMRC_LINES) + "\n"


def _emit_dep(name: str, spec) -> str:
    """Emit one `[tool.poetry.dependencies]` line, rewriting ployglots paths."""
    if isinstance(spec, str):
        return f'{name} = "{spec}"'
    if isinstance(spec, dict):
        if "path" in spec:
            p = spec["path"]
            if p.startswith("../../ployglots/"):
                p = "./" + p[len("../../"):]
            develop = bool(spec.get("develop", False))
            return f'{name} = {{ path = "{p}", develop = {"true" if develop else "false"} }}'
        if "extras" in spec and "version" in spec:
            extras = ", ".join(f'"{e}"' for e in spec["extras"])
            return f'{name} = {{ extras = [{extras}], version = "{spec["version"]}" }}'
        raise SystemExit(
            f"regenerate.py: unhandled dep shape for {name}: {spec!r}\n"
            f"Extend _emit_dep() to cover this case."
        )
    raise SystemExit(f"regenerate.py: unsupported spec type for {name}: {type(spec).__name__}")


def build_pyproject() -> str:
    with SRV_FASTAPI.open("rb") as f:
        data = tomllib.load(f)
    deps = data["tool"]["poetry"]["dependencies"]

    lines: list[str] = [_HEADER_PYPROJECT.rstrip(), ""]
    lines += [
        "[tool.poetry]",
        'name = "mta-ployglot-server-root"',
        'version = "0.0.0"',
        'description = "Docker-only root Poetry manifest for Dockerfile.fastapi. '
        "Generated by .bin/docker/regenerate.py from server/fastapi/pyproject.toml.\"",
        'authors = ["Think Eloquent"]',
        'license = "MIT"',
        "package-mode = false",
        "",
        "[tool.poetry.dependencies]",
    ]
    for name, spec in deps.items():
        lines.append(_emit_dep(name, spec))
    lines += [
        "",
        "[build-system]",
        'requires = ["poetry-core>=1.8"]',
        'build-backend = "poetry.core.masonry.api"',
    ]
    return "\n".join(lines) + "\n"


def _write_if_needed(path: Path, content: str, *, apply: bool) -> bool:
    """Return True if content matches what's on disk, False if drift."""
    existing = path.read_text() if path.exists() else None
    if existing == content:
        return True
    if apply:
        path.write_text(content)
        print(f"updated: {path.relative_to(ROOT)}")
    else:
        print(f"DRIFT: {path.relative_to(ROOT)}", file=sys.stderr)
    return False


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--apply", action="store_true", help="write files (default)")
    group.add_argument("--check", action="store_true", help="exit 1 on any drift; no writes")
    args = parser.parse_args()
    apply = not args.check  # --apply is the default

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    targets = [
        (OUT_PNPM_WS, build_pnpm_workspace()),
        (OUT_PKG_JSON, build_pkg_json()),
        (OUT_NPMRC, build_npmrc()),
        (OUT_PYPROJECT, build_pyproject()),
    ]

    all_match = True
    for path, content in targets:
        if not _write_if_needed(path, content, apply=apply):
            all_match = False

    if args.check:
        return 0 if all_match else 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
