#!/usr/bin/env bash
# .bin/docker/validate-node.sh — generated by
# scripts/workspace/generate-package-validate.sh. DO NOT EDIT BY HAND.
#
# Asserts every node sibling listed below is installed in the image's
# runtime (venv for python, node_modules for node). Replaces count-based
# smoke checks (`pip list --editable | wc -l`) which can't name a missing
# sibling. Sourced from .bin/docker/pnpm-workspace.yaml; regenerate via
# scripts/workspace/generate-package-validate.sh after editing.
set -euo pipefail

PKGS=(
  @ployglot/fastify-server
  @mta/print-routes-fastify
  @polyglot/fetch-http-client
  @org/env-resolve
  @ployglot/app-yaml-loader
  @ployglot/runtime-template-resolver
  @ployglot/app-yaml-from-context
  @ployglot/app-yaml-config
  @ployglot/app-yaml-fetch-config
)
EXPECTED=9
MISSING=()

# require.resolve fails with a non-zero exit when the package can't be
# located on the resolution path — exactly the signal we want.
GOT=0
for p in "${PKGS[@]}"; do
  if node -e "require.resolve('$p')" >/dev/null 2>&1; then
    GOT=$((GOT + 1))
  else
    MISSING+=("$p")
  fi
done
if [[ "$GOT" -ne "$EXPECTED" ]]; then
  echo "FAIL: expected $EXPECTED node siblings, got $GOT" >&2
  for p in "${MISSING[@]}"; do echo "  MISSING: $p" >&2; done
  exit 1
fi
echo "OK: $EXPECTED sibling packages installed"
