#!/usr/bin/env bash
# .bin/docker/validate-python.sh — generated by
# scripts/workspace/generate-package-validate.sh. DO NOT EDIT BY HAND.
#
# Asserts every python sibling listed below is installed in the image's
# runtime (venv for python, node_modules for node). Replaces count-based
# smoke checks (`pip list --editable | wc -l`) which can't name a missing
# sibling. Sourced from .bin/docker/pyproject.docker.toml; regenerate via
# scripts/workspace/generate-package-validate.sh after editing.
set -euo pipefail

PKGS=(
  thinkeloquent-fastapi-server
  print-routes-fastapi
  polyglot-fetch-http-client
  env-resolve
  app-yaml-loader
  runtime-template-resolver
  app-yaml-from-context
  app-yaml-config
  app-yaml-fetch-config
)
EXPECTED=9
MISSING=()

# Single pip-show invocation is fastest; per-name follow-up only when count
# disagrees so we can report exactly which sibling is absent.
GOT=$(pip show "${PKGS[@]}" 2>/dev/null | grep -c "^Name:" || true)
if [[ "$GOT" -ne "$EXPECTED" ]]; then
  for p in "${PKGS[@]}"; do
    pip show "$p" >/dev/null 2>&1 || MISSING+=("$p")
  done
  echo "FAIL: expected $EXPECTED python siblings, got $GOT" >&2
  for p in "${MISSING[@]}"; do echo "  MISSING: $p" >&2; done
  exit 1
fi
echo "OK: $EXPECTED sibling packages installed"
