#!/usr/bin/env bash
# docker-compose-emit.sh — emit docker-compose.yml from workspace.toml.
#
# The compose file is COMMITTED but generated. The two runtime services
# (fastify, fastapi) are stable — they're the orchestration shell's
# entrypoints — so the emitter encodes them as a fixed template. The
# REGISTRY-DRIVEN piece is `build.additional_contexts`: every entry in
# workspace.toml is exposed to both Dockerfiles as a named build context
# (`ployglot-<name>` → `<shell_path>`). A new sibling added to the
# registry → a new context available to docker on the next bootstrap,
# with no hand-edit of the compose file.
#
# Why additional_contexts and not new services / volumes:
#   - Most siblings are libraries (api-*, pkg-*, tools-*), not runnables.
#     Forcing them into compose as services would be misleading.
#   - additional_contexts is the canonical compose-v2 way to say "this
#     directory is an input to the build, addressable by name from any
#     Dockerfile" — Dockerfiles can `COPY --from=ployglot-<name> ...`
#     without hardcoding paths into ployglots/.
#   - Build context stays "." so existing `COPY ployglots/<name>/...`
#     lines keep working. The change is purely additive.
#
# Modes:
#   (default)    write docker-compose.yml at the repo root
#   --check      compare a regenerated compose against the committed file;
#                exit non-zero with a diff if they differ.
#
# Determinism: identical workspace.toml → byte-identical docker-compose.yml.
#
# Exits:
#   0   wrote (or --check passed)
#   65  registry validation failed
#   66  registry not found
#   69  --check failed: docker-compose.yml is stale
#   127 missing python3 / tomllib
set -euo pipefail
IFS=$'\n\t'

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"
REG="${WORKSPACE_REGISTRY:-$ROOT_DIR/workspace.toml}"
OUT="${WORKSPACE_COMPOSE_OUT:-$ROOT_DIR/docker-compose.yml}"

MODE="emit"
case "${1:-}" in
  --check) MODE="check" ;;
  -h|--help)
    cat <<USAGE
docker-compose-emit.sh — emit docker-compose.yml from workspace.toml

USAGE:
  docker-compose-emit.sh           # write docker-compose.yml
  docker-compose-emit.sh --check   # CI guard: fail if committed file is stale

ENV:
  WORKSPACE_REGISTRY               path to workspace.toml (default: <root>/workspace.toml)
  WORKSPACE_COMPOSE_OUT            output path           (default: <root>/docker-compose.yml)
USAGE
    exit 0 ;;
  "") ;;
  *) echo "unknown flag: $1" >&2; exit 64 ;;
esac

if ! command -v python3 >/dev/null 2>&1; then
  echo "missing: python3 (3.11+ for tomllib)" >&2
  exit 127
fi

if [[ ! -f "$REG" ]]; then
  echo "FAIL: registry not found: $REG" >&2
  exit 66
fi

if [[ -x "$SELF_DIR/validate.sh" ]]; then
  if ! "$SELF_DIR/validate.sh" "$REG" >/dev/null; then
    echo "FAIL: $REG did not validate" >&2
    exit 65
  fi
fi

TMP="$(mktemp -t docker-compose.XXXXXX.yml)"
trap 'rm -f "$TMP"' EXIT

# YAML is rendered by hand-formatted Python (no PyYAML dep — none of the
# other emitters carry one). The fixed body matches today's hand-curated
# docker-compose.yml byte-for-byte, except for:
#   - the leading "do not edit" header
#   - build.additional_contexts blocks injected from the registry
python3 - "$REG" >"$TMP" <<'PY'
import sys, tomllib

with open(sys.argv[1], "rb") as f:
    doc = tomllib.load(f)

entries = doc.get("entry", [])

def additional_contexts(indent: str) -> str:
    """Render `additional_contexts:` keyed by `ployglot-<name>` → ./<shell_path>.

    indent is the prefix applied to every emitted line (matches the
    surrounding `build:` block's nesting). Sibling order matches the
    registry order, so re-runs are byte-identical.
    """
    if not entries:
        return f"{indent}additional_contexts: {{}}\n"
    lines = [f"{indent}additional_contexts:"]
    for e in entries:
        # Key format `ployglot-<name>` matches `COPY --from=ployglot-<name>`
        # in Dockerfiles; values are paths relative to the build context.
        lines.append(f'{indent}  ployglot-{e["name"]}: ./{e["shell_path"]}')
    return "\n".join(lines) + "\n"

print("# docker-compose.yml — GENERATED by scripts/workspace/docker-compose-emit.sh")
print("# DO NOT EDIT BY HAND. Source of truth: workspace.toml + this emitter.")
print("# Re-emit:  bash scripts/workspace/docker-compose-emit.sh")
print("# CI gate:  bash scripts/workspace/docker-compose-emit.sh --check")
print("#")
print("# Two-service polyglot bootstrap stack. Build context is the repo root so")
print("# both Dockerfiles can COPY from ployglots/. Every registered sibling is")
print("# also exposed as `ployglot-<name>` via build.additional_contexts so")
print("# Dockerfiles can `COPY --from=ployglot-<name> ...` without hardcoding")
print("# paths inside ployglots/.")
print("#")
print("# Default host ports: 5100 (fastify), 5200 (fastapi). Override via .env.")
print("# Container-internal ports are fixed at 3000 (fastify) and 8080 (fastapi).")
print("#")
print("# Hardening (limited, not production):")
print("#   - init: true  -> docker-init as PID 1 for correct signal forwarding")
print("#   - read_only: true  -> immutable root FS; writable scratch via tmpfs")
print("#   - cap_drop: [ALL]  -> drop all Linux capabilities")
print("#   - security_opt: no-new-privileges:true  -> block setuid escalation")
print("#   - restart: unless-stopped")
print()
print("services:")
print("  fastify:")
print("    image: mta-fastify:local")
print("    container_name: mta-fastify")
print("    build:")
print("      context: .")
print("      dockerfile: server/fastify/Dockerfile")
sys.stdout.write(additional_contexts("      "))
print("    environment:")
print('      PORT: "3000"')
print("      NODE_ENV: production")
print('      POLYGLOT_DEBUG: "1"')
print("    ports:")
print('      - "${FASTIFY_PORT:-5100}:3000"')
print("    init: true")
print("    read_only: true")
print("    tmpfs:")
print("      - /tmp:size=64m,mode=1777")
print("    cap_drop:")
print("      - ALL")
print("    security_opt:")
print("      - no-new-privileges:true")
print("    healthcheck:")
print("      test:")
print("        - CMD")
print("        - node")
print("        - -e")
print("        - \"require('http').get('http://127.0.0.1:3000/healthz', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))\"")
print("      interval: 10s")
print("      timeout: 3s")
print("      start_period: 5s")
print("      retries: 5")
print("    restart: unless-stopped")
print()
print("  fastapi:")
print("    image: mta-fastapi:local")
print("    container_name: mta-fastapi")
print("    build:")
print("      context: .")
print("      dockerfile: server/fastapi/Dockerfile")
sys.stdout.write(additional_contexts("      "))
print("    environment:")
print('      PORT: "8080"')
print('      POLYGLOT_DEBUG: "1"')
print("    ports:")
print('      - "${FASTAPI_PORT:-5200}:8080"')
print("    init: true")
print("    read_only: true")
print("    tmpfs:")
print("      - /tmp:size=64m,mode=1777")
print("    cap_drop:")
print("      - ALL")
print("    security_opt:")
print("      - no-new-privileges:true")
print("    healthcheck:")
print("      test:")
print("        - CMD")
print("        - python")
print("        - -c")
print("        - \"import urllib.request,sys; r=urllib.request.urlopen('http://127.0.0.1:8080/healthz', timeout=2); sys.exit(0 if r.status == 200 else 1)\"")
print("      interval: 10s")
print("      timeout: 3s")
print("      start_period: 5s")
print("      retries: 5")
print("    restart: unless-stopped")
PY

if [[ "$MODE" == "check" ]]; then
  if [[ ! -f "$OUT" ]]; then
    echo "FAIL: $OUT does not exist; run scripts/workspace/docker-compose-emit.sh" >&2
    exit 69
  fi
  if ! diff -u "$OUT" "$TMP" >/tmp/docker-compose-diff.$$ 2>&1; then
    echo "FAIL: $OUT is stale relative to $REG" >&2
    echo "  re-run: bash scripts/workspace/docker-compose-emit.sh" >&2
    echo "----- diff (committed → regenerated) -----" >&2
    cat /tmp/docker-compose-diff.$$ >&2
    rm -f /tmp/docker-compose-diff.$$
    exit 69
  fi
  rm -f /tmp/docker-compose-diff.$$
  echo "ok: $OUT in sync with $REG"
  exit 0
fi

mv "$TMP" "$OUT"
trap - EXIT
echo "wrote $OUT"
