#!/usr/bin/env bash
# emit-go-work.sh — derive go.work from workspace.toml.
#
# Filters entries where language ∈ {go, mixed}. Workspace mode only — never
# emits or modifies any sibling's `go.mod` (no `replace` injection). The
# go.work file is .gitignore'd so the orchestration shell's main branch
# stays free of generated workspace files.
#
# Toolchain version is configurable via WORKSPACE_GO_VERSION (default: 1.22).
#
# Exits:
#   0   wrote (or empty case — no Go entries, no file written)
#   71  defensive guard tripped (replace directive leaked into output)
#   78  output file is git-tracked (configuration error)
#   127 missing python3 / tomllib
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"
REG="${WORKSPACE_REGISTRY:-$ROOT_DIR/workspace.toml}"
OUT="${WORKSPACE_GO_WORK_OUT:-$ROOT_DIR/go.work}"
GO_VER="${WORKSPACE_GO_VERSION:-1.22}"

if ! command -v python3 >/dev/null 2>&1; then
  echo "missing: python3 (3.11+ for tomllib)" >&2
  exit 127
fi

OUT_REL="${OUT##$ROOT_DIR/}"
if git -C "$ROOT_DIR" ls-files --error-unmatch "$OUT_REL" >/dev/null 2>&1; then
  echo "FAIL: $OUT is tracked in git; add to .gitignore first" >&2
  exit 78
fi

PKGS=()
while IFS= read -r line; do
  [[ -n "$line" ]] && PKGS+=("$line")
done < <(python3 - "$REG" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    doc = tomllib.load(f)
for e in doc.get("entry", []):
    if e.get("language") in ("go", "mixed"):
        print(e["shell_path"])
PY
)

if [[ ${#PKGS[@]} -eq 0 ]]; then
  rm -f "$OUT"
  echo "no Go entries; skipped writing $OUT"
  exit 0
fi

TMP="$(mktemp -t go-work.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

{
  echo "// >>> generated by emit-go-work.sh — do not edit <<<"
  echo "go $GO_VER"
  echo
  echo "use ("
  for p in "${PKGS[@]}"; do printf "\t./%s\n" "$p"; done
  echo ")"
  echo "// <<< end emit-go-work.sh <<<"
} > "$TMP"

# Defensive: forbid `replace` directives from ever appearing.
if grep -Eq '^[[:space:]]*replace[[:space:]]' "$TMP"; then
  echo "FAIL: emitter wrote a replace directive — bug" >&2
  exit 71
fi

mv "$TMP" "$OUT"
trap - EXIT

echo "wrote $OUT (${#PKGS[@]} modules, go $GO_VER)"
