#!/usr/bin/env bash
# emit-pnpm.sh — derive pnpm-workspace.yaml from workspace.toml.
#
# Filters entries where language ∈ {node, mixed}. Idempotent: re-running
# produces byte-identical output. Refuses to run if pnpm-workspace.yaml is
# already tracked in git (must be .gitignore'd, per the orchestration shell's
# "main is empty" rule).
#
# Exits:
#   0   wrote (or no-op)
#   78  output file is git-tracked (configuration error)
#   127 missing python3 / tomllib
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"
REG="${WORKSPACE_REGISTRY:-$ROOT_DIR/workspace.toml}"
OUT="${WORKSPACE_PNPM_OUT:-$ROOT_DIR/pnpm-workspace.yaml}"

SENTINEL_OPEN="# >>> generated by emit-pnpm.sh — do not edit between these markers <<<"
SENTINEL_CLOSE="# <<< end emit-pnpm.sh <<<"

if ! command -v python3 >/dev/null 2>&1; then
  echo "missing: python3 (3.11+ for tomllib)" >&2
  exit 127
fi

# Refuse if the output is git-tracked. The orchestration shell's main branch
# must stay free of generated workspace files. Compute the relative path
# without GNU `realpath --relative-to` (BSD realpath on macOS lacks it).
OUT_REL="${OUT##$ROOT_DIR/}"
if git -C "$ROOT_DIR" ls-files --error-unmatch "$OUT_REL" >/dev/null 2>&1; then
  echo "FAIL: $OUT is tracked in git; add to .gitignore first" >&2
  exit 78
fi

# bash 3.2-compatible array fill (macOS ships bash 3.2; mapfile is bash 4+).
PKGS=()
while IFS= read -r line; do
  [[ -n "$line" ]] && PKGS+=("$line")
done < <(python3 - "$REG" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    doc = tomllib.load(f)
for e in doc.get("entry", []):
    if e.get("language") in ("node", "mixed"):
        print(e["shell_path"])
PY
)

# Write to a temp file then mv for atomicity.
TMP="$(mktemp -t pnpm-workspace.XXXXXX.yaml)"
trap 'rm -f "$TMP"' EXIT

{
  echo "$SENTINEL_OPEN"
  echo "packages:"
  if [[ ${#PKGS[@]} -eq 0 ]]; then
    echo "  []"
  else
    for p in "${PKGS[@]}"; do printf "  - '%s'\n" "$p"; done
  fi
  echo "$SENTINEL_CLOSE"
} > "$TMP"

mv "$TMP" "$OUT"
trap - EXIT

echo "wrote $OUT (${#PKGS[@]} packages)"
