#!/usr/bin/env bash
# emit-make-vars.sh — derive Makefile.entries from workspace.toml.
#
# Generates four space-separated `make` variables — NODE_PKGS, PY_PKGS,
# GO_PKGS, RUST_PKGS — listing every sibling's `shell_path` for that
# language family. Mixed entries are added to all four buckets so the
# per-language Makefile fragments naturally pick them up.
#
# The output file is .gitignore'd; bootstrap.sh invokes this emitter as
# part of its emitter chain so fragments always read fresh data.
#
# Idempotent: re-running produces byte-identical output.
#
# Exits:
#   0   wrote
#   78  output file is git-tracked (configuration error)
#   127 missing python3 / tomllib
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"
REG="${WORKSPACE_REGISTRY:-$ROOT_DIR/workspace.toml}"
OUT="${WORKSPACE_MAKE_VARS_OUT:-$ROOT_DIR/Makefile.entries}"

if ! command -v python3 >/dev/null 2>&1; then
  echo "missing: python3 (3.11+ for tomllib)" >&2
  exit 127
fi

OUT_REL="${OUT##$ROOT_DIR/}"
if git -C "$ROOT_DIR" ls-files --error-unmatch "$OUT_REL" >/dev/null 2>&1; then
  echo "FAIL: $OUT is tracked in git; add to .gitignore first" >&2
  exit 78
fi

TMP="$(mktemp -t makefile-entries.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

python3 - "$REG" >"$TMP" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    doc = tomllib.load(f)

buckets = {"node": [], "python": [], "go": [], "rust": []}
for e in doc.get("entry", []):
    lang = e.get("language")
    p = e["shell_path"]
    if lang == "mixed":
        for k in buckets:
            buckets[k].append(p)
    elif lang in buckets:
        buckets[lang].append(p)

print("# >>> generated by emit-make-vars.sh — do not edit <<<")
# Use `:=` to pin values at parse time; fragments read these via $(NODE_PKGS) etc.
print("NODE_PKGS :=", " ".join(buckets["node"]))
print("PY_PKGS   :=", " ".join(buckets["python"]))
print("GO_PKGS   :=", " ".join(buckets["go"]))
print("RUST_PKGS :=", " ".join(buckets["rust"]))
print("# <<< end emit-make-vars.sh <<<")
PY

mv "$TMP" "$OUT"
trap - EXIT

echo "wrote $OUT"
