#!/usr/bin/env bash
# emit-cargo.sh — derive a virtual root Cargo.toml from workspace.toml.
#
# Filters entries where language ∈ {rust, mixed}. Writes a virtual workspace:
#   [workspace]
#   resolver = "3"
#   members  = [<sorted shell_path list>]
# No [package] section. members[] is sorted alphabetically for deterministic
# diffs. If a sibling crate is itself a Cargo workspace, only its root path
# is listed (avoiding "package found in multiple workspaces" errors).
#
# Exits:
#   0   wrote (or empty case — no Rust entries, no file written)
#   71  defensive guard tripped ([package] section leaked into output)
#   78  output file is git-tracked (configuration error)
#   127 missing python3 / tomllib
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SELF_DIR/../.." && pwd)"
REG="${WORKSPACE_REGISTRY:-$ROOT_DIR/workspace.toml}"
OUT="${WORKSPACE_CARGO_OUT:-$ROOT_DIR/Cargo.toml}"

if ! command -v python3 >/dev/null 2>&1; then
  echo "missing: python3 (3.11+ for tomllib)" >&2
  exit 127
fi

OUT_REL="${OUT##$ROOT_DIR/}"
if git -C "$ROOT_DIR" ls-files --error-unmatch "$OUT_REL" >/dev/null 2>&1; then
  echo "FAIL: $OUT is tracked in git; add to .gitignore first" >&2
  exit 78
fi

# detect_kind: classify a sibling's Cargo.toml as workspace, package, or missing.
detect_kind() {
  local cargo="$1/Cargo.toml"
  if [[ ! -f "$cargo" ]]; then echo "missing"; return; fi
  if grep -q '^\[workspace\]' "$cargo"; then
    echo "workspace"
  else
    echo "package"
  fi
}

# Read entries (shell_path + local_path pairs) for rust/mixed.
ENTRIES=()
while IFS=$'\t' read -r shell_path local_path; do
  [[ -n "$shell_path" ]] && ENTRIES+=("$shell_path"$'\t'"$local_path")
done < <(python3 - "$REG" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    doc = tomllib.load(f)
for e in doc.get("entry", []):
    if e.get("language") in ("rust", "mixed"):
        print(f"{e['shell_path']}\t{e['local_path']}")
PY
)

# Filter: keep entries whose Cargo.toml exists; emit `warn:` for missing.
# bash 3.2 trips on `"${ENTRIES[@]}"` under `set -u` when the array is empty;
# the `${arr[@]+...}` form expands to nothing in that case.
PKGS=()
for ent in ${ENTRIES[@]+"${ENTRIES[@]}"}; do
  shell_path="${ent%%$'\t'*}"
  local_path="${ent##*$'\t'}"
  # Resolve local_path relative to ROOT_DIR if not absolute.
  if [[ "$local_path" != /* ]]; then
    abs_local="$ROOT_DIR/$local_path"
  else
    abs_local="$local_path"
  fi
  kind="$(detect_kind "$abs_local")"
  case "$kind" in
    workspace|package)
      # Both shapes get listed once at shell_path. Workspace siblings are nested
      # under our root and Cargo handles them transparently; per-package siblings
      # are direct members. (Documented in Story 02/04 task 02.)
      PKGS+=("$shell_path")
      ;;
    missing)
      echo "warn: skipping ${shell_path} — Cargo.toml not found at ${local_path}; run bootstrap first" >&2
      ;;
  esac
done

# Sort alphabetically for deterministic diffs.
if [[ ${#PKGS[@]} -gt 0 ]]; then
  IFS=$'\n' SORTED=($(printf '%s\n' "${PKGS[@]}" | sort))
  PKGS=("${SORTED[@]}")
fi

if [[ ${#PKGS[@]} -eq 0 ]]; then
  rm -f "$OUT"
  echo "no Rust entries with Cargo.toml; skipped writing $OUT"
  exit 0
fi

TMP="$(mktemp -t cargo-toml.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

{
  echo "# >>> generated by emit-cargo.sh — do not edit <<<"
  echo "[workspace]"
  echo "resolver = \"3\""
  echo "members = ["
  for p in "${PKGS[@]}"; do printf "  \"%s\",\n" "$p"; done
  echo "]"
  echo "# <<< end emit-cargo.sh <<<"
} > "$TMP"

# Defensive: forbid a [package] section from ever leaking in.
if grep -q '^\[package\]' "$TMP"; then
  echo "FAIL: emitted Cargo.toml contains [package] — bug" >&2
  exit 71
fi

mv "$TMP" "$OUT"
trap - EXIT

echo "wrote $OUT (${#PKGS[@]} crates)"
